---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  NLBArnNumber:
    Type: String
    Description: Provide ARN  for the Load balancer created for API server
Resources:
    MyVpcLink:
        Type: AWS::ApiGateway::VpcLink
        Properties:
            Description: "api sever vpclink"
            Name: "apilink-apiserver-dev"
            TargetArns:
               - !Ref NLBArnNumber
               
Outputs:
  jyapigatewayvpclink:
    Description: Logic id for the vpclink
    Value: !Ref MyVpcLink
    Export: 
      Name: jy-apigateway-vpclink