AWSTemplateFormatVersion: 2010-09-09
Description: S3 bucekt for static assets/cdn
Parameters:
  ACMGlobalCertArn:
    Type: String
    Description: Provide ARN for certificate to be use from us-east-1 zone

Resources:

  s3bucketglobalstatic:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      # need something long and globally unique.
      BucketName: "images.juvyou.com"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              # has to be AES256 - kms can not be used for bucket with distribution
              SSEAlgorithm: 'AES256'

      # no access to public what-so-ever.      
      PublicAccessBlockConfiguration:
        BlockPublicAcls : true
        BlockPublicPolicy : true
        IgnorePublicAcls : true
        RestrictPublicBuckets : true

  CloudFrontOriginIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'origin identity'

  BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: images.juvyou.com
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginIdentity}'
              Action: 's3:GetObject'
              Resource: arn:aws:s3:::images.juvyou.com/*
      DependsOn:
        - "publicDistribution"
  
  publicDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:  
        Aliases:
          - images.juvyou.com
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: '/default.jpg'
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: '/default.jpg'
        Origins:
          - DomainName: !Sub images.juvyou.com.s3.${AWS::Region}.amazonaws.com
            Id: S3-images.juvyou.com
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOriginIdentity}'
        Enabled: 'true'
        Comment: Distribution for the static content
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: S3-images.juvyou.com
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          # certificate below is for juvyou.com from us-east-1 not from current region.
          #AcmCertificateArn: "arn:aws:acm:us-east-1:949501214913:certificate/289b6988-e9cb-477e-95df-b7ccf42fc1ea"
          AcmCertificateArn: !Ref ACMGlobalCertArn

          SslSupportMethod: "sni-only"
          MinimumProtocolVersion: "TLSv1.2_2021"
          #CloudFrontDefaultCertificate: 'true'

Outputs:
  distributionname2:
    Description: the cloudfront url for static images assets
    Value: publicDistribution.DomainName
    Export: 
      Name: jy-distribution-name-dev

