AWSTemplateFormatVersion: '2010-09-09'
Description: Create a beanstalk server for the API Server. Pick a key to be used with ec2 hosts.
Parameters:
    KeyName:
      Type: AWS::EC2::KeyPair::KeyName
      Description: "Name of an existing SSH Keypair to access the instance"

Resources:
  APIServerApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: AWS Elastic Beanstalk APIServer Application
  APIServerApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName:
        Ref: APIServerApplication
      Description: AWS ElasticBeanstalk APIServer Application Version
      SourceBundle:
        S3Bucket: !Sub "jy-cf-setup-base-code-${AWS::Region}"
        S3Key: api.zip
  APIServerConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName:
        Ref: APIServerApplication
      Description: AWS ElasticBeanstalk APIServer Configuration Template
      OptionSettings:
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: '1'
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: '4'
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced

      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value: !Ref MyInstanceProfile
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: EC2KeyName
        Value: !Ref KeyName
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: RootVolumeSize
        Value: "30"

      - Namespace: aws:elasticbeanstalk:environment
        OptionName: LoadBalancerType
        Value: 'network'

      - Namespace: aws:ec2:vpc
        OptionName: VPCId
        Value: !ImportValue jy-vpc-varenvname

      - Namespace: aws:ec2:vpc
        OptionName: Subnets
        Value: !Sub 
          - "${suba}, ${subb}, ${subc}"
          - { suba: !ImportValue jy-vpc-varenvname-subnet-apia, subb: !ImportValue jy-vpc-varenvname-subnet-apib, subc: !ImportValue jy-vpc-varenvname-subnet-apic }
      - Namespace: aws:ec2:instances
        OptionName: InstanceTypes
        Value: 't2.medium'

      - Namespace: aws:ec2:instances
        OptionName: InstanceTypes
        Value: 't2.medium'

      # don't want this to be visible publically. should resolve to internal ip.
      - Namespace: aws:ec2:vpc
        OptionName: ELBScheme
        Value: 'internal'

      # how changes will be rolled out to intances
      - Namespace: aws:elasticbeanstalk:command
        OptionName: DeploymentPolicy
        Value: 'Rolling'

      # ASG settings
      # scale based on CPU utilization
      - Namespace: aws:autoscaling:trigger
        OptionName: MeasureName
        Value: 'CPUUtilization'
      # lower threshold is 20% CPU
      - Namespace: aws:autoscaling:trigger
        OptionName: LowerThreshold
        Value: '20'
      # polling period is every 3 mins  
      - Namespace: aws:autoscaling:trigger
        OptionName: Period
        Value: '3'
      # two such a period should pass for trigger to happen
      - Namespace: aws:autoscaling:trigger
        OptionName: EvaluationPeriods
        Value: '2'
      # unit of operation is Percetage of CPU util.
      - Namespace: aws:autoscaling:trigger
        OptionName: Unit
      # uppper limit when ASG will add the instance
        Value: 'Percent'
      - Namespace: aws:autoscaling:trigger
        OptionName: UpperThreshold
        Value: '75'
      # Log needs to be stramed into cloud watch
      - Namespace: aws:elasticbeanstalk:cloudwatch:logs
        OptionName: StreamLogs
        Value: 'True'
      # retain the logs for 7 days
      - Namespace: aws:elasticbeanstalk:cloudwatch:logs
        OptionName: RetentionInDays
        Value: '7'

      # added new once - Oct 15th.. let's see how they work
      - Namespace: aws:elasticbeanstalk:cloudwatch:logs:health
        OptionName: HealthStreamingEnabled
        Value: 'True'
      - Namespace: aws:elasticbeanstalk:cloudwatch:logs:health
        OptionName: DeleteOnTerminate
        Value: 'False'
      - Namespace: aws:elasticbeanstalk:cloudwatch:logs:health
        OptionName: RetentionInDays
        Value: '7'

      # - Namespace: elasticbeanstalk:healthreporting:system
      #   OptionName: SystemType
      #   Value: 'enhanced'
      # # end - added new once - Oct 15th.. let's see how they work

      # environment variables to pass in
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: "PORT"
        Value: '8080'


      SolutionStackName: "64bit Amazon Linux 2 v3.2.7 running Corretto 8"
      # SolutionStackName: "64bit Amazon Linux 2 v3.3.5 running Python 3.8"

  APIServerEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      # let's give it a name
      EnvironmentName: "beanstalk-apiserver-varenvname"
      ApplicationName:
        Ref: APIServerApplication
      Description: AWS ElasticBeanstalk APIServer Environment
      TemplateName:
        Ref: APIServerConfigurationTemplate
      VersionLabel:
        Ref: APIServerApplicationVersion
  
  # instance profile that uses the role we created earlier.  
  # has standard bs related policies and access to KMS/S3 buckets
  MyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles:
        - !ImportValue jy-ec2apiserverrolename-varenvname

Outputs:
  somevariable:
    Description: Some description
    Value: 
      Ref: "APIServerConfigurationTemplate"
  endpointurl:
    Description: the beanstalk endpoint url
    Value:  !GetAtt  APIServerEnvironment.EndpointURL
    Export:
      Name: jy-branstalkapiseverurl-varenvname

