AWSTemplateFormatVersion: '2010-09-09'
Description: Beanstalk for Machine Learning module. Python based.
Parameters:
    KeyName:
      Type: AWS::EC2::KeyPair::KeyName
      Description: "Name of an existing SSH Keypair to access the instance"

Resources:
  MLServerApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: AWS Elastic Beanstalk MLServer Application
  MLServerApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName:
        Ref: MLServerApplication
      Description: AWS ElasticBeanstalk MLServer Application Version
      SourceBundle:
        S3Bucket: !Sub "jy-cf-setup-base-code-${AWS::Region}"
        S3Key: recommend.zip
  MLServerConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName:
        Ref: MLServerApplication
      Description: AWS ElasticBeanstalk MLServer Configuration Template
      OptionSettings:
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: '1'
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: '4'
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced

      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: IamInstanceProfile
        Value: !Ref MyInstanceProfile
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: EC2KeyName
        Value: !Ref KeyName

      - Namespace: aws:elasticbeanstalk:environment
        OptionName: LoadBalancerType
        Value: 'network'

      - Namespace: aws:ec2:vpc
        OptionName: VPCId
        Value: !ImportValue jy-vpc-varenvname

      - Namespace: aws:ec2:vpc
        OptionName: Subnets
        Value: !Sub 
          - "${suba}, ${subb}, ${subc}"
          - { suba: !ImportValue jy-vpc-varenvname-subnet-mla, subb: !ImportValue jy-vpc-varenvname-subnet-mlb, subc: !ImportValue jy-vpc-varenvname-subnet-mlc }
      - Namespace: aws:ec2:instances
        OptionName: InstanceTypes
        Value: 't2.medium'

      # don't want this to be visible publically. should resolve to internal ip.
      - Namespace: aws:ec2:vpc
        OptionName: ELBScheme
        Value: 'internal'

      # how changes will be rolled out to intances
      - Namespace: aws:elasticbeanstalk:command
        OptionName: DeploymentPolicy
        Value: 'Rolling'

      # ASG settings
      # scale based on CPU utilization
      - Namespace: aws:autoscaling:trigger
        OptionName: MeasureName
        Value: 'CPUUtilization'
      # lower threshold is 20% CPU
      - Namespace: aws:autoscaling:trigger
        OptionName: LowerThreshold
        Value: '20'
      # polling period is every 3 mins  
      - Namespace: aws:autoscaling:trigger
        OptionName: Period
        Value: '3'
      # two such a period should pass for trigger to happen
      - Namespace: aws:autoscaling:trigger
        OptionName: EvaluationPeriods
        Value: '2'
      # unit of operation is Percetage of CPU util.
      - Namespace: aws:autoscaling:trigger
        OptionName: Unit
      # uppper limit when ASG will add the instance
        Value: 'Percent'
      - Namespace: aws:autoscaling:trigger
        OptionName: UpperThreshold
        Value: '75'
      # Log needs to be stramed into cloud watch
      - Namespace: aws:elasticbeanstalk:cloudwatch:logs
        OptionName: StreamLogs
        Value: 'True'
      # retain the logs for 7 days
      - Namespace: aws:elasticbeanstalk:cloudwatch:logs
        OptionName: RetentionInDays
        Value: '7'

      # added new once - Oct 15th.. let's see how they work
      - Namespace: aws:elasticbeanstalk:cloudwatch:logs:health
        OptionName: HealthStreamingEnabled
        Value: 'True'
      - Namespace: aws:elasticbeanstalk:cloudwatch:logs:health
        OptionName: DeleteOnTerminate
        Value: 'False'
      - Namespace: aws:elasticbeanstalk:cloudwatch:logs:health
        OptionName: RetentionInDays
        Value: '7'

      # environment variables to pass in
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: "PORT"
        Value: '8000'


      #SolutionStackName: "64bit Amazon Linux 2 v3.2.5 running Corretto 8"
      SolutionStackName: "64bit Amazon Linux 2 v3.3.7 running Python 3.8"

  MLServerEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      # let's give it a name
      EnvironmentName: "beanstalk-mlserver-dev"
      ApplicationName:
        Ref: MLServerApplication
      Description: AWS ElasticBeanstalk MLServer Environment
      TemplateName:
        Ref: MLServerConfigurationTemplate
      VersionLabel:
        Ref: MLServerApplicationVersion
  
  # instance profile that uses the role we created earlier.  
  # has standard bs related policies and access to KMS/S3 buckets
  MyInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles:
        - !ImportValue jy-ec2apiserverrolename-varenvname

Outputs:
  somevariable:
    Description: Some description
    Value: 
      Ref: "MLServerConfigurationTemplate"
  endpointurl:
    Description: the beanstalk endpoint url
    Value:   !GetAtt MLServerEnvironment.EndpointURL
    Export:
      Name: jy-branstalkmlseverurl-varenvname

