AWSTemplateFormatVersion: '2010-09-09'
Description: Create a hosted zone for application.local
Resources:
  DNS: 
    Type: "AWS::Route53::HostedZone"
    Properties: 
      HostedZoneConfig: 
        Comment: 'My hosted zone for application.local'
      Name: 'application.local'
      VPCs: 
        - 
          VPCId: !ImportValue jy-vpc-varenvname
          VPCRegion: !Ref "AWS::Region"
          
      HostedZoneTags: 
        - 
          Key: 'attachedto'
          Value: 'varenvname-vpc'

  dnsbsapidev:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : !Ref DNS
      Name: bs-api-varenvname.application.local
      ResourceRecords:
      - !ImportValue jy-branstalkapiseverurl-varenvname
      TTL: 900
      Type: CNAME

  dnsbsconfigdev:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : !Ref DNS
      Name: bs-config-varenvname.application.local
      ResourceRecords:
      - !ImportValue jy-branstalkconfigseverurl-varenvname
      TTL: 900
      Type: CNAME

  dnsbsmldev:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId : !Ref DNS
      Name: bs-ml-varenvname.application.local
      ResourceRecords:
      - !ImportValue jy-branstalkmlseverurl-varenvname
      TTL: 900
      Type: CNAME