AWSTemplateFormatVersion: "2010-09-09"
Description: API Gateway for the environment
Parameters:
  RegionCertARN:
    Type: String
    Description: Provide ARN  for the SSL certificate located in the same region
Resources:
    ApiGatewayResourceRecomm:
        Type: "AWS::ApiGateway::Resource"
        Properties:
            RestApiId: !Ref ApiGatewayRestApi
            PathPart: "recommender"
            ParentId: !GetAtt ApiGatewayRestApi.RootResourceId

    ApiGatewayResourceRecommProxy:
        Type: "AWS::ApiGateway::Resource"
        Properties:
            RestApiId: !Ref ApiGatewayRestApi
            PathPart: "{proxy+}"
            ParentId: !Ref ApiGatewayResourceRecomm

    ApiGatewayResourceApidocs:
        Type: "AWS::ApiGateway::Resource"
        Properties:
            RestApiId: !Ref ApiGatewayRestApi
            PathPart: "api-docs"
            ParentId: !GetAtt ApiGatewayRestApi.RootResourceId

    ApiGatewayResourceImages:
        Type: "AWS::ApiGateway::Resource"
        Properties:
            RestApiId: !Ref ApiGatewayRestApi
            PathPart: "images"
            ParentId: !GetAtt ApiGatewayRestApi.RootResourceId

    ApiGatewayResourceProxy0:
        Type: "AWS::ApiGateway::Resource"
        Properties:
            RestApiId: !Ref ApiGatewayRestApi
            PathPart: "{proxy+}"
            ParentId: !Ref ApiGatewayResourceApidocs

    ApiGatewayResourceProxy1:
        Type: "AWS::ApiGateway::Resource"
        Properties:
            RestApiId: !Ref ApiGatewayRestApi
            PathPart: "{proxy+}"
            ParentId: !GetAtt ApiGatewayRestApi.RootResourceId

    ApiGatewayResourceProxy3:
        Type: "AWS::ApiGateway::Resource"
        Properties:
            RestApiId: !Ref ApiGatewayRestApi
            PathPart: "{proxy+}"
            ParentId: !Ref ApiGatewayResourceImages

    ApiGatewayRestApi:
        Type: "AWS::ApiGateway::RestApi"
        Properties:
            BinaryMediaTypes:
            - "image/jpeg"
            - "image/jpg"
            - "image/png"
            - "image/gif"
            - "multipart/form-data"
            
            DisableExecuteApiEndpoint : "true"
            Name: "api-varenvname"
            ApiKeySourceType: "HEADER"
            EndpointConfiguration: 
                Types: 
                  - "REGIONAL"


    Deployment:
      Type: 'AWS::ApiGateway::Deployment'
      Properties:
        RestApiId: !Ref ApiGatewayRestApi
        Description: My deployment
      DependsOn:
        - "ApiGatewayMethod0"
        - "ApiGatewayMethod"
        - "ApiGatewayMethod2"
        # - "ApiGatewayMethod3"
        - "ApiGatewayMethod4"

    ApiGatewayStage:
        Type: "AWS::ApiGateway::Stage"
        Properties:
            StageName: "v1"
            DeploymentId: !Ref Deployment
            RestApiId: !Ref ApiGatewayRestApi
            CacheClusterEnabled: false
            MethodSettings: 
              - ResourcePath: "/*"
                HttpMethod: "*"
                MetricsEnabled: false
                DataTraceEnabled: false
                CachingEnabled: false
            TracingEnabled: false

    ApiGatewayMethod0:
    
        Type: "AWS::ApiGateway::Method"
        Properties:
            RestApiId: !Ref ApiGatewayRestApi
            ResourceId: !Ref ApiGatewayResourceRecommProxy
            HttpMethod: "ANY"
            AuthorizationType: "NONE"
            ApiKeyRequired: false
            RequestParameters: 
                "method.request.path.proxy": true
            MethodResponses: 
              - 
                ResponseModels: 
                    "application/json": !Ref ApiGatewayModel2
                StatusCode: "200"
            Integration: 
                CacheKeyParameters: 
                  - "method.request.path.proxy"
                CacheNamespace: !Ref ApiGatewayResourceRecomm
                ConnectionId: !ImportValue jy-vpclink-recoserver-varenvname
                ConnectionType: "VPC_LINK"
                IntegrationHttpMethod: "ANY"
                IntegrationResponses: 
                  - StatusCode: "200"
                PassthroughBehavior: "WHEN_NO_MATCH"
                RequestParameters: 
                    "integration.request.path.proxy": "method.request.path.proxy"
                TimeoutInMillis: 29000
                Type: "HTTP_PROXY"
                Uri: !Sub 
                - "http://${mlurl}/recommender/{proxy}"
                - mlurl: !ImportValue jy-branstalkmlseverurl-varenvname

    ApiGatewayMethod:

        Type: "AWS::ApiGateway::Method"
        Properties:
            RestApiId: !Ref ApiGatewayRestApi
            ResourceId: !Ref ApiGatewayResourceProxy0
            HttpMethod: "GET"
            AuthorizationType: "NONE"
            ApiKeyRequired: false
            RequestParameters: 
                "method.request.path.proxy": true
            MethodResponses: 
              - 
                ResponseModels: 
                    "application/json": !Ref ApiGatewayModel2
                StatusCode: "200"
            Integration: 
                CacheKeyParameters: 
                  - "method.request.path.proxy"
                CacheNamespace: !Ref ApiGatewayResourceProxy0
                ConnectionId: !ImportValue jy-apigateway-vpclink-varenvname
                ConnectionType: "VPC_LINK"
                IntegrationHttpMethod: "GET"
                IntegrationResponses: 
                  - StatusCode: "200"
                PassthroughBehavior: "WHEN_NO_MATCH"
                RequestParameters: 
                    "integration.request.path.proxy": "method.request.path.proxy"
                TimeoutInMillis: 29000
                Type: "HTTP_PROXY"
                Uri: !Sub 
                - "http://${apiurl}/api-docs/{proxy}"
                - apiurl: !ImportValue jy-branstalkapiseverurl-varenvname

    ApiGatewayMethod2:
        Type: "AWS::ApiGateway::Method"
        Properties:
            RestApiId: !Ref ApiGatewayRestApi
            ResourceId: !Ref ApiGatewayResourceProxy1
            HttpMethod: "ANY"
            AuthorizationType: "NONE"
            ApiKeyRequired: false
            RequestParameters: 
                "method.request.path.proxy": true
            Integration: 
                CacheKeyParameters: 
                  - "method.request.path.proxy"
                CacheNamespace: !Ref ApiGatewayResourceProxy1
                ConnectionId: !ImportValue jy-apigateway-vpclink-varenvname
                ConnectionType: "VPC_LINK"
                IntegrationHttpMethod: "ANY"
                IntegrationResponses: 
                  - StatusCode: "200"
                PassthroughBehavior: "WHEN_NO_MATCH"
                RequestParameters: 
                    "integration.request.path.proxy": "method.request.path.proxy"
                TimeoutInMillis: 29000
                Type: "HTTP_PROXY"
                Uri: !Sub 
                - "http://${apiurl}/{proxy}"
                - apiurl: !ImportValue jy-branstalkapiseverurl-varenvname

    ApiGatewayMethod4:
        Type: "AWS::ApiGateway::Method"
        Properties:
            RestApiId: !Ref ApiGatewayRestApi
            ResourceId: !Ref ApiGatewayResourceProxy3
            HttpMethod: "GET"
            AuthorizationType: "NONE"
            ApiKeyRequired: false
            RequestParameters: 
                "method.request.path.proxy": true
            MethodResponses: 
              - 
                ResponseModels: 
                    "application/json": !Ref ApiGatewayModel2
                StatusCode: "200"
            Integration: 
                CacheKeyParameters: 
                  - "method.request.path.proxy"
                CacheNamespace: !Ref ApiGatewayResourceProxy3
                ConnectionId: !ImportValue jy-apigateway-vpclink-varenvname
                ConnectionType: "VPC_LINK"
                IntegrationHttpMethod: "GET"
                IntegrationResponses: 
                  - StatusCode: "200"
                PassthroughBehavior: "WHEN_NO_MATCH"
                RequestParameters: 
                    "integration.request.path.proxy": "method.request.path.proxy"
                TimeoutInMillis: 29000
                Type: "HTTP_PROXY"
                Uri: !Sub 
                - "http://${apiurl}/images/{proxy}"
                - apiurl: !ImportValue jy-branstalkapiseverurl-varenvname

    ApiGatewayBasePathMapping:
        Type: "AWS::ApiGateway::BasePathMapping"
        Properties:
            BasePath: "(none)"
            DomainName: "varenvname.somethingweird.tech"
            RestApiId: !Ref ApiGatewayRestApi
            Stage: !Ref ApiGatewayStage

    ApiGatewayDomainName:
        Type: "AWS::ApiGateway::DomainName"
        Properties:
            DomainName: "varenvname.somethingweird.tech"
            EndpointConfiguration: 
                Types: 
                  - "REGIONAL"
            MutualTlsAuthentication:
                #TruststoreUri: "s3://app-setup/truststore-dev/root-ca-dev-bundle02.txt"
                TruststoreUri: !Sub "s3://jy-cf-setup-api-truststore-${AWS::Region}/root-ca-bundle.txt"
            SecurityPolicy: "TLS_1_2"
            RegionalCertificateArn: !Ref RegionCertARN

    ApiGatewayModel:
        Type: "AWS::ApiGateway::Model"
        Properties:
            RestApiId: !Ref ApiGatewayRestApi
            Name: "Error2"
            Description: "This is a default error schema model"
            Schema: |
                {
                  "$schema" : "http://json-schema.org/draft-04/schema#",
                  "title" : "Error Schema",
                  "type" : "object",
                  "properties" : {
                    "message" : { "type" : "string" }
                  }
                }
            ContentType: "application/json"

    ApiGatewayModel2:
        Type: "AWS::ApiGateway::Model"
        Properties:
            RestApiId: !Ref ApiGatewayRestApi
            Name: "Empty2"
            Description: "This is a default empty schema model"
            Schema: |
                {
                  "$schema": "http://json-schema.org/draft-04/schema#",
                  "title" : "Empty Schema",
                  "type" : "object"
                }
            ContentType: "application/json"


